// Code generated by "filtersf --type=bool"; DO NOT EDIT.

package filtersf

import util "github.com/t3reezhou/golang_util"

func Bool(ss []bool, fs []func(i int) bool, shouldReturn bool) [][]bool {
	result := make([][]bool, len(fs)+1)
	util.FiltersF(len(ss), fs, func(i, j int) { result[i] = append(result[i], ss[j]) }, shouldReturn)
	return result
}
