// Code generated by "filtersf --type=int16"; DO NOT EDIT.

package filtersf

import util "github.com/t3reezhou/golang_util"

func Int16(ss []int16, fs []func(i int) bool, shouldReturn bool) [][]int16 {
	result := make([][]int16, len(fs)+1)
	util.FiltersF(len(ss), fs, func(i, j int) { result[i] = append(result[i], ss[j]) }, shouldReturn)
	return result
}
