// Code generated by "filtersf --type=string"; DO NOT EDIT.

package filtersf

import util "github.com/t3reezhou/golang_util"

func String(ss []string, fs []func(i int) bool, shouldReturn bool) [][]string {
	result := make([][]string, len(fs)+1)
	util.FiltersF(len(ss), fs, func(i, j int) { result[i] = append(result[i], ss[j]) }, shouldReturn)
	return result
}
