// Code generated by "filtersf --type=uint16"; DO NOT EDIT.

package filtersf

import util "github.com/t3reezhou/golang_util"

func Uint16(ss []uint16, fs []func(i int) bool, shouldReturn bool) [][]uint16 {
	result := make([][]uint16, len(fs)+1)
	util.FiltersF(len(ss), fs, func(i, j int) { result[i] = append(result[i], ss[j]) }, shouldReturn)
	return result
}
