// Code generated by "filtersf --type=uint8"; DO NOT EDIT.

package filtersf

import util "github.com/t3reezhou/golang_util"

func Uint8(ss []uint8, fs []func(i int) bool, shouldReturn bool) [][]uint8 {
	result := make([][]uint8, len(fs)+1)
	util.FiltersF(len(ss), fs, func(i, j int) { result[i] = append(result[i], ss[j]) }, shouldReturn)
	return result
}
