// Code generated by "collection --type=bool"; DO NOT EDIT.

package collection

import "github.com/t3reezhou/golang_util/filter"

func Bool(length int, do func(i int) bool, funcs ...CollecitonFunc) []bool {
	var o CollecitonOptions
	for _, f := range funcs {
		f(&o)
	}
	if o.judge == nil {
		o.judge = func(i int) bool { return true }
	}
	result := make([]bool, length)
	filter.Filter(length, o.judge, func(i int) { result[i] = do(i) })
	return result
}
