// Code generated by "collection --type=int64"; DO NOT EDIT.

package collection

import "github.com/t3reezhou/golang_util/filter"

func Int64(length int, do func(i int) int64, funcs ...CollecitonFunc) []int64 {
	var o CollecitonOptions
	for _, f := range funcs {
		f(&o)
	}
	if o.judge == nil {
		o.judge = func(i int) bool { return true }
	}
	result := make([]int64, length)
	filter.Filter(length, o.judge, func(i int) { result[i] = do(i) })
	return result
}
