// Code generated by "collection --type=uint8"; DO NOT EDIT.

package collection

import "github.com/t3reezhou/golang_util/filter"

func Uint8(length int, do func(i int) uint8, funcs ...CollecitonFunc) []uint8 {
	var o CollecitonOptions
	for _, f := range funcs {
		f(&o)
	}
	if o.judge == nil {
		o.judge = func(i int) bool { return true }
	}
	result := make([]uint8, length)
	filter.Filter(length, o.judge, func(i int) { result[i] = do(i) })
	return result
}
