// Code generated by "filtersd --type=int64"; DO NOT EDIT.

package filtersd

import util "github.com/t3reezhou/golang_util"

func Int64(ss []int64, fs []func(i int) bool, shouldReturn bool) [][]int64 {
	result := make([][]int64, len(fs)+1)
	util.FiltersD(len(ss), fs, func(i, j int) { result[i] = append(result[i], ss[j]) }, shouldReturn)
	return result
}
