// Code generated by "filtersd --type=uint64"; DO NOT EDIT.

package filtersd

import util "github.com/t3reezhou/golang_util"

func Uint64(ss []uint64, fs []func(i int) bool, shouldReturn bool) [][]uint64 {
	result := make([][]uint64, len(fs)+1)
	util.FiltersD(len(ss), fs, func(i, j int) { result[i] = append(result[i], ss[j]) }, shouldReturn)
	return result
}
